// <auto-generated />
using System;
using Carpool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carpool.Data.Migrations
{
    [DbContext(typeof(CarpoolDbContext))]
    partial class CarpoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carpool.Core.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("integer");

                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<int>("RideId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("RideId", "PassengerId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Booking_NumberOfSeats_Positive", "\"NumberOfSeats\" > 0");
                        });
                });

            modelBuilder.Entity("Carpool.Core.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer");

                    b.Property<int>("RideId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("RideId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("Ratings", t =>
                        {
                            t.HasCheckConstraint("CK_Rating_Score_Range", "\"Score\" >= 1 AND \"Score\" <= 5");
                        });
                });

            modelBuilder.Entity("Carpool.Core.Entities.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PricePerSeat")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Scheduled");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rides", t =>
                        {
                            t.HasCheckConstraint("CK_Ride_AvailableSeats_Range", "\"AvailableSeats\" >= 0 AND \"AvailableSeats\" <= \"TotalSeats\"");

                            t.HasCheckConstraint("CK_Ride_TotalSeats_Positive", "\"TotalSeats\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartureTime = new DateTime(2030, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Jerusalem",
                            DriverId = 2,
                            EstimatedDurationMinutes = 60,
                            Origin = "Tel Aviv",
                            PricePerSeat = 25.00m,
                            RowVersion = 0u,
                            Status = "Scheduled",
                            TotalSeats = 3,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartureTime = new DateTime(2030, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Tel Aviv",
                            DriverId = 3,
                            EstimatedDurationMinutes = 90,
                            Origin = "Haifa",
                            PricePerSeat = 30.00m,
                            RowVersion = 0u,
                            Status = "Scheduled",
                            TotalSeats = 2,
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("Carpool.Core.Entities.RideTag", b =>
                {
                    b.Property<int>("RideId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("RideId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RideTags");

                    b.HasData(
                        new
                        {
                            RideId = 1,
                            TagId = 1
                        },
                        new
                        {
                            RideId = 1,
                            TagId = 4
                        },
                        new
                        {
                            RideId = 2,
                            TagId = 2
                        });
                });

            modelBuilder.Entity("Carpool.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"OwnerId\" IS NULL");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasFilter("\"OwnerId\" IS NOT NULL");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Quiet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PetsAllowed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SmokingForbidden"
                        });
                });

            modelBuilder.Entity("Carpool.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("User");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@carpool.dev",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEBUbLMKM4BpncNZwJpDpoOdp7Iyxiec5eZYskgkZMkOCzUATnykIFmg52+g+igRoUQ==",
                            PhoneNumber = "+972500000001",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@carpool.dev",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Cohen",
                            PasswordHash = "AQAAAAIAAYagAAAAEBUbLMKM4BpncNZwJpDpoOdp7Iyxiec5eZYskgkZMkOCzUATnykIFmg52+g+igRoUQ==",
                            PhoneNumber = "+972500000002",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@carpool.dev",
                            FirstName = "Bob",
                            IsActive = true,
                            LastName = "Levi",
                            PasswordHash = "AQAAAAIAAYagAAAAEBUbLMKM4BpncNZwJpDpoOdp7Iyxiec5eZYskgkZMkOCzUATnykIFmg52+g+igRoUQ==",
                            PhoneNumber = "+972500000003",
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol@carpool.dev",
                            FirstName = "Carol",
                            IsActive = true,
                            LastName = "Mizrahi",
                            PasswordHash = "AQAAAAIAAYagAAAAEBUbLMKM4BpncNZwJpDpoOdp7Iyxiec5eZYskgkZMkOCzUATnykIFmg52+g+igRoUQ==",
                            PhoneNumber = "+972500000004",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("Carpool.Core.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Vehicles", t =>
                        {
                            t.HasCheckConstraint("CK_Vehicle_PassengerCapacity_Positive", "\"PassengerCapacity\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LicensePlate = "111-11-111",
                            Manufacturer = "Toyota",
                            Model = "Corolla",
                            OwnerId = 2,
                            PassengerCapacity = 4
                        },
                        new
                        {
                            Id = 2,
                            LicensePlate = "222-22-222",
                            Manufacturer = "Honda",
                            Model = "Civic",
                            OwnerId = 3,
                            PassengerCapacity = 3
                        },
                        new
                        {
                            Id = 3,
                            LicensePlate = "333-33-333",
                            Manufacturer = "Mazda",
                            Model = "3",
                            OwnerId = 4,
                            PassengerCapacity = 5
                        });
                });

            modelBuilder.Entity("Carpool.Core.Entities.Booking", b =>
                {
                    b.HasOne("Carpool.Core.Entities.User", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carpool.Core.Entities.Ride", "Ride")
                        .WithMany("Bookings")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("Carpool.Core.Entities.Rating", b =>
                {
                    b.HasOne("Carpool.Core.Entities.User", "Driver")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carpool.Core.Entities.User", "Reviewer")
                        .WithMany("RatingsGiven")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carpool.Core.Entities.Ride", "Ride")
                        .WithMany("Ratings")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Reviewer");

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("Carpool.Core.Entities.Ride", b =>
                {
                    b.HasOne("Carpool.Core.Entities.User", "Driver")
                        .WithMany("RidesAsDriver")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carpool.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("Rides")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Carpool.Core.Entities.RideTag", b =>
                {
                    b.HasOne("Carpool.Core.Entities.Ride", "Ride")
                        .WithMany("RideTags")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carpool.Core.Entities.Tag", "Tag")
                        .WithMany("RideTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Carpool.Core.Entities.Tag", b =>
                {
                    b.HasOne("Carpool.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Carpool.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("Carpool.Core.Entities.User", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Carpool.Core.Entities.Ride", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Ratings");

                    b.Navigation("RideTags");
                });

            modelBuilder.Entity("Carpool.Core.Entities.Tag", b =>
                {
                    b.Navigation("RideTags");
                });

            modelBuilder.Entity("Carpool.Core.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RatingsGiven");

                    b.Navigation("RatingsReceived");

                    b.Navigation("RidesAsDriver");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Carpool.Core.Entities.Vehicle", b =>
                {
                    b.Navigation("Rides");
                });
#pragma warning restore 612, 618
        }
    }
}
